SwitchbackTech/compass

packages/backend/src/__tests__/gcal.util.test.ts, packages/backend/src/common/errors/handlers/error.express.handler.ts, packages/backend/src/common/services/gcal/gcal.utils.ts
=> 🐞 Fix User Id Error Parsing

.github/dependabot.yml
=> 👷ci: update dependabot.yml

packages/web/src/common/apis/compass.api.ts
=> Refresh Window after 601 Error

packages/scripts/src/commands/build.ts, packages/scripts/src/common/cli.utils.ts
Handles scenario when user is building web
for prod by prompting for the clientId
(instead of using the one from the staging
.env)
=> :bug: Fix(build-web): prompt for clientId

.prettierignore, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE
=> :memo: Cleanup root files

packages/web/src/ducks/events/selectors/draft.selectors.ts, packages/web/src/ducks/events/selectors/event.selectors.ts
=> ⚡️Perf: memoize event selectors

packages/scripts/src/commands/build.ts, yarn.lock
=> 🐛 Fix: husky postinstall error during node build

packages/web/src/views/CmdPalette/CmdPalette.tsx
=> :bug: Fix(web): update Code link to open in new tab

packages/web/src/common/types/web.event.types.ts, packages/web/src/views/Calendar/hooks/draft/useDraftUtil.ts
=> 🐛 Fix event flip logic

packages/web/src/views/Calendar/components/Event/Grid/GridEvent/GridEvent.tsx, packages/web/src/views/Calendar/components/Event/styled.ts
=> 🐛 fix(web): increase precision of event scaler

.github/workflows/test.yml, README.md
=> 👷‍♂️ ci: use node v20 in test workflow

packages/web/package.json, packages/web/src/views/Calendar/components/LeftSidebar/SomedaySection/SomedayEvents/SomedayEvent.tsx, packages/web/src/views/Forms/EventForm/EventForm.tsx, packages/web/src/views/Forms/hooks/useEventForm.ts, yarn.lock
=> 🐛 Fix: Trap focus in form

packages/web/src/__tests__/__mocks__/mock.render.tsx, packages/web/src/__tests__/__mocks__/tabbable.js, packages/web/src/components/DatePicker/DatePicker.tsx, packages/web/src/views/Forms/EventForm/DateTimeSection/DatePickers.tsx, packages/web/src/views/Forms/EventForm/DateTimeSection/DateTimeSection.tsx, packages/web/src/views/Forms/EventForm/DateTimeSection/index.ts, packages/web/src/views/Forms/EventForm/EventForm.test.tsx, packages/web/src/views/Forms/EventForm/EventForm.tsx
This pull request includes several changes aimed at improving the DatePicker component and its integration within the EventForm in order to fix #187. The most important changes include the addition of a new `DatePickers` component, updates to the `DateTimeSection` and `EventForm` components, and the addition of a new test for the EventForm.
* [`packages/web/src/components/DatePicker/DatePicker.tsx`](diffhunk://#diff-d6415b53742385129e9066bbe9a85ef066defaedd348b3c8548ca8adff802bc1R78-R79): Added `role="combobox"` and `aria-label="datepicker"` to enhance accessibility.
* [`packages/web/src/views/Forms/EventForm/DateTimeSection/DatePickers.tsx`](diffhunk://#diff-a41798c57a8fb058ea61f8be96695eefc3ee3eca85dc0a16d64ff7cb518901f3R1-R199): Introduced a new `DatePickers` component to manage the …
=> 🐛 Fix: prevent multiple datepickers from rendering simultaneously

packages/web/src/common/utils/event.util.ts, packages/web/src/common/utils/grid.util.ts, packages/web/src/ducks/events/selectors/event.selectors.ts, packages/web/src/views/Calendar/components/Event/Grid/GridEvent/GridEvent.tsx, packages/web/src/views/Calendar/components/Grid/AllDayRow/AllDayEvent.tsx, packages/web/src/views/Calendar/components/Grid/AllDayRow/AllDayEvents.tsx, packages/web/src/views/Calendar/hooks/event/getPosition.ts
This pull request is a followup to the type / dev issues mentioned in the comments of #234 (issue #213). It  includes several updates to the event utilities and components in the calendar view. The changes mainly focus on improving type safety, handling optimistic events, and refining the event positioning logic.
**Type safety improvements:**
* [`packages/web/src/ducks/events/selectors/event.selectors.ts`](diffhunk://#diff-2f1ff4d8b51c8332c7b3da45090624d33d8fbc3f60a809ec96342cafb6777a66R8-R19): Introduced `Schema_GridEvent_NoPosition` type to omit the `position` field from `Schema_GridEvent` and updated the `selectAllDayEvents` selector to use this type.
**Handling optimistic events:**
* [`packages/web/src/common/utils/event.util.ts`](diffhunk://#diff-0b8ca0d3429ed8c7fdf27f61eca39c52fd7b9e …
=> ♻️ Refactor: Update overlapping event type safety

package.json
=> 🧹 Chore: Specify package manager version in package.json

packages/web/src/views/Calendar/hooks/grid/useGridEventMouseHold.ts
Closes https://github.com/SwitchbackTech/compass/issues/279
When clicking an event, an event click is sometimes treated as a drag because the user's mouse accidentally shook while clicking.
This PR implements a move threshold to treat these accidental shakes as mere clicks and not drags.
https://github.com/user-attachments/assets/2ad3c33a-f4ac-486f-9f50-cc3c8d9adf94
[Peek 2025-02-28 07-33.webm](https://github.com/user-attachments/assets/26ccf961-3830-477c-b373-4dbd8571aa2a)
=> 🐛 Fix: Implement grid event move threshold

packages/web/src/common/utils/grid.util.ts, packages/web/src/common/utils/position.util.ts, packages/web/src/views/Calendar/components/Event/Grid/GridEvent/GridEvent.tsx, packages/web/src/views/Calendar/components/Grid/AllDayRow/AllDayEvent.tsx
Closes issue https://github.com/SwitchbackTech/compass/issues/291
[Peek 2025-03-08 22-53.webm](https://github.com/user-attachments/assets/feaf14c6-5b02-4f9a-b838-31e451f27db9)
[Peek 2025-03-08 19-52.webm](https://github.com/user-attachments/assets/98dad142-6557-4002-a650-b6845e2e878e)
=> 🐛 Fix: all day events overlapping

packages/web/src/views/Calendar/hooks/grid/useGridEventMouseDown.test.ts
See https://github.com/SwitchbackTech/compass/issues/316
=> hotfix(web): disable test expect statement

packages/web/src/views/Calendar/components/Draft/grid/hooks/useGridMouseUp.ts
Closes https://github.com/SwitchbackTech/compass/issues/305
The issue was that mouse up callbacks are not being listened to if we mouse up outside the main grid area, so the only solution is to attach a global event listener ("root" div that react injects its code into)
[Peek 2025-03-21 13-10.webm](https://github.com/user-attachments/assets/c138672a-1fbb-408f-b3f5-bf45366a8488)
[Peek 2025-03-21 13-09.webm](https://github.com/user-attachments/assets/1cc295c0-3c55-47e6-9379-43f47b40335f)
=> 🐛 Fix: reduce all day row and main grid event listeners into a single root event listener

packages/backend/src/__tests__/factories/gcal.event.factory.ts, packages/backend/src/__tests__/factories/gcal.factory.ts, packages/backend/src/__tests__/fixtures/recurring/create.json, packages/backend/src/__tests__/fixtures/recurring/edit.all-2.json, packages/backend/src/__tests__/fixtures/recurring/edit.all.json, packages/backend/src/__tests__/fixtures/recurring/edit.single-2.json, packages/backend/src/__tests__/fixtures/recurring/edit.single-3.json, packages/backend/src/__tests__/fixtures/recurring/edit.single.json, packages/backend/src/__tests__/fixtures/recurring/edit.this-and-future.instance.json, packages/backend/src/__tests__/fixtures/recurring/edit.this-and-future.no-instances.json, packages/backend/src/__tests__/fixtures/recurring/recurring-events.md, packages/backend/src/__tests__/helpers/mock.db.setup.ts, packages/backend/src/common/constants/error.constants.ts, packages/backend/src/common/services/mongo.service.ts, packages/backend/src/sync/services/import/sync.import.test.ts, packages/backend/src/sync/services/import/sync.import.ts, packages/backend/src/sync/services/import/sync.import.types.ts, packages/backend/src/sync/services/import/sync.import.util.test.ts, packages/backend/src/sync/services/import/sync.import.util.ts, packages/backend/src/sync/services/log/sync.logger.ts, packages/backend/src/sync/services/notify/sync.notify.recurring.test.ts, packages/backend/src/sync/services/notify/sync.notify.test.setup.ts, packages/backend/src/sync/services/notify/sync.notify.test.ts, packages/backend/src/sync/services/notify/sync.notify.ts, packages/backend/src/sync/services/sync.service.ts, packages/backend/src/sync/util/sync.queries.ts
Predecessor to #318 
Closes #327 
This pull request refactors and enhances the mock data generation for Google Calendar events in the backend tests. The changes include renaming and restructuring factories, adding new mock data generation functions, and updating fixtures to reflect the new structure.
* [`packages/backend/src/__tests__/factories/event.factory.ts`](diffhunk://#diff-57c23c23a425398d85dc71350c7f7653ccff230fb1de38db7897091a0d65785aL1-L45): Removed the old event generation functions.
* [`packages/backend/src/__tests__/factories/gcal.event.factory.ts`](diffhunk://#diff-92b19a416ca679c927afbdc9c82c617f5077586e841336b73243da125fe3b0e8R1-R123): Added new functions for generating regular, recurring, and paginated events, and for creating mock Google Calendar events with more …
=> 🧪 Test: Setup gcal notification test and doc

packages/web/src/ducks/events/sagas/somday.sagas.ts
Closes https://github.com/SwitchbackTech/compass/issues/297
=> 🐛 Fix: Remove `recurrence` field when converting a someday event to a grid event

packages/web/src/views/Calendar/components/Event/Grid/GridEvent/GridEvent.tsx, packages/web/src/views/Calendar/components/Grid/AllDayRow/AllDayEvent.tsx, packages/web/src/views/Forms/EventForm/DateControlsSection/RecurrenceSection/RecurrenceSection.tsx, packages/web/src/views/Forms/EventForm/DateControlsSection/RecurrenceSection/styled.ts
Closes #352 
https://github.com/user-attachments/assets/cdfec9da-0534-43fe-b173-f0401cd4396a
=> ✨ Feat: Disable edits for recurring events 

packages/web/src/common/types/util.types.ts, packages/web/src/common/types/web.event.types.ts, packages/web/src/common/utils/event.util.ts, packages/web/src/views/Calendar/components/Draft/hooks/actions/useDraftActions.ts, packages/web/src/views/Calendar/components/Grid/MainGrid/MainGridEvents.tsx, packages/web/src/views/Calendar/hooks/grid/useGridEventMouseDown.test.ts, packages/web/src/views/Calendar/hooks/grid/useGridEventMouseDown.ts
Closes https://github.com/SwitchbackTech/compass/issues/282
When dragging an event, account for the cursor's initial mouse position when computing position during drag
https://github.com/user-attachments/assets/073c8637-985d-4e9e-86a3-d97f60be1619
https://github.com/user-attachments/assets/31c015b8-bbcd-48d8-96c6-b9d71c12eaea
=> ✨ Feat: Maintain mouse cursor offset while dragging event

packages/web/src/views/Forms/SomedayEventForm/SomedayEventForm.test.tsx, packages/web/src/views/Forms/SomedayEventForm/SomedayEventForm.tsx
Closes https://github.com/SwitchbackTech/compass/issues/344
- Fix someday event form not saving when pressing the enter key
- Match the hotkey listener implementation with the Grid Event Form component for consistency
- Implement unit tests
=> 🐛 Fix: Someday event form not saving when pressing enter key on keyboard

packages/web/src/components/Text/styled.ts, packages/web/src/views/Forms/EventForm/DateControlsSection/RecurrenceSection/RecurrenceSection.tsx, packages/web/src/views/Forms/EventForm/DateControlsSection/RecurrenceSection/styled.ts
Closes https://github.com/SwitchbackTech/compass/issues/382
This PR provides minor enhancements to edit recurrence section UX
=> ✨ Feat: better UX for recurrence section

packages/backend/src/__tests__/helpers/mock.db.queries.ts, packages/backend/src/common/types/backend.event.types.ts, packages/backend/src/common/validators/validate.event.ts, packages/backend/src/common/validators/validate.ts, packages/backend/src/event/services/recur/repo/recur.event.repo.util.ts, packages/backend/src/event/services/recur/util/recur.util.test.ts, packages/backend/src/event/services/recur/util/recur.util.ts, packages/backend/src/sync/services/import/sync.import.full.test.ts, packages/backend/src/sync/services/import/sync.import.series.test.ts, packages/backend/src/sync/services/import/sync.import.ts, packages/backend/src/sync/services/sync/__tests__/gcal.sync.processor.test.util.ts, packages/backend/src/sync/services/sync/__tests__/gcal.sync.processor.upsert.base.test.ts
Closes #385, which was caused by
- a prop being overridden by the base, resulting in the target instance not being updated
- using strings instead of `ObjectId` when assigning ids 
Adds utility and schema for better typechecking on the backend
✅ DELETE ALL
✅ DELETE ONE
✅ DELETE THIS AND FOLLOWING
✅ CREATE ALL
✅ UPDATE ONE REGULAR
✅  UPDATE ONE INSTANCE (this PR)
✅ UPDATE ALL
✅ UPDATE THIS AND FOLLOWING
❌ parses custom RRULEs
❌ bugs: #378 and likely others
----
This pull request introduces significant changes to improve type safety, validation, and modularity in handling event data, particularly focusing on recurring events and their synchronization. Key updates include the introduction of a new `Event_API` type, enhanced validation mechanisms, and the refactoring of utility functions for …
=> 🐛 Fix: preserve instance gEventId during update

packages/backend/src/sync/services/import/all/import.all.gcal.ts, packages/core/src/mappers/map.event.to-compass.test.ts, packages/core/src/mappers/map.event.to-gcal.test.ts, packages/core/src/mappers/map.event.ts
Closes #390 
In an earlier version of the app we used 'relations' instead of 'relationships'. When an older user tried using the app now, it'd fail validation because of the unknown value.
Now, if we find a priority that isn't part of the `Priorities` enum, we default to the `UNASSIGNED` value.
----
This pull request introduces error handling improvements, test restructuring, and refactoring of priority handling for Google Calendar event mapping. The most significant changes include adding error handling to the `fetchAndProcessEventsPageByPage` function, splitting tests into separate files for better organization, and centralizing priority handling logic into a new `getPriority` function.
* Added a `try-catch` block to the `fetchAndProcessEventsPageByPage` function to log and rethrow …
=> 🐛 Fix: map unsupported priority to UNASSIGNED

packages/web/src/views/Calendar/components/Header/HeaderNote/HeaderNote.tsx
Closes https://github.com/SwitchbackTech/compass/issues/401
Fixes issue with header note editing. When clicking somewhere other than the end of the text, the keystrokes after the 1st keystroke always get sent to the end of the text rather than the original position
=> 🐛 Fix: HeaderNote not respecting cursor position when editing

packages/web/src/views/Calendar/components/Sidebar/SomedayTab/MonthSection/MonthSection.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/WeekSection/WeekSection.tsx
=> Feat/issue#389 

packages/web/src/components/ContextMenu/ContextMenuItems.tsx, packages/web/src/views/Calendar/components/Draft/grid/GridDraft.tsx, packages/web/src/views/Calendar/components/Draft/hooks/actions/useDraftActions.ts, packages/web/src/views/Calendar/hooks/shortcuts/useShortcuts.ts, packages/web/src/views/Forms/EventForm/EventForm.tsx, packages/web/src/views/Forms/EventForm/types.ts
Closes https://github.com/SwitchbackTech/compass/issues/191
Implement a duplicate event feature where user can right click to duplicate event or press key combination `META + D` to achieve the same.
https://github.com/user-attachments/assets/ad39051c-27a5-4218-a9e7-16a23f2ca1ca
=> ✨ Feat: Duplicate event

README.md, packages/core/src/mappers/map.event.ts
Updates the README as part of #311
=> 📜 Docs: update README

AGENTS.md
Closes #435 
This pull request adds a new `AGENTS.md` file to document the project structure, conventions, setup, and testing guidelines for the repository.
Documentation changes:
* [`AGENTS.md`](diffhunk://#diff-a54ff182c7e8acf56acfd6e4b9c3ff41e2c41a31c9b211b2deb9df75d9a478f9R1-R22): Introduced a new file outlining the project overview, including the monorepo structure with Yarn workspaces, conventions for contributing, setup instructions (e.g., using Node LTS and Yarn), and testing practices (e.g., co-locating tests with code and running `yarn test` before submitting a PR).
=> ✨ feat: add AGENTS.md guide with project setup and testing instructions

packages/backend/src/waitlist/controller/waitlist.controller-check.test.ts, packages/backend/src/waitlist/controller/waitlist.controller.ts, packages/web/src/common/apis/waitlist.api.ts, packages/web/src/views/Login/Login.tsx
=> ✨ Feat: Allow active users to bypass waitlist 

README.md
=> 📜 Docs: add job posting for backend engineer position to README

packages/web/src/views/Login/Login.tsx
Another follow up to #461. I didn't implement it correctly in my latest PR (#461)
=> 🐛 fix: only show waitlist message if user isn't already active

packages/web/src/common/types/web.event.types.ts, packages/web/src/common/utils/__tests__/someday.util.test.ts, packages/web/src/common/utils/someday.util.ts, packages/web/src/common/validators/someday.event.validator.ts, packages/web/src/views/Calendar/components/Draft/sidebar/hooks/useSidebarActions.ts, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEvents.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEventsContainer/SomedayEventsContainer.tsx
Closes https://github.com/SwitchbackTech/compass/issues/488
=> ✨ Feat: Update someday event start-end date when DnD'ing to different section

packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEventsContainer/Dropzone.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEventsContainer/SomedayEventsContainer.tsx
Closes https://github.com/SwitchbackTech/compass/issues/487
https://github.com/user-attachments/assets/95124794-e009-4ae8-99b0-8e5c78e39d48
https://github.com/user-attachments/assets/07b58fa6-c8a3-404c-aa8b-0643905374c5
=> ✨ Feat: Implement Dropzone to provide visual indication of where to drop while DnD'ing someday events

packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEventsContainer/SomedayEventsContainer.tsx
Closes https://github.com/SwitchbackTech/compass/issues/515
=> ✨ Feat: Hide someday event add button when dragging

packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEventsContainer/AddSomedayEvent.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEventsContainer/SomedayEventsContainer.tsx
Closes https://github.com/SwitchbackTech/compass/issues/523
=> 🐛 Fix: prevent rendering tooltip for add someday btn when dragging someday event

packages/web/src/components/TooltipIconButton/TooltipIconButton.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEventContainer/SomedayEventContainer.tsx, packages/web/src/views/Forms/EventForm/MigrateBackwardButton.tsx, packages/web/src/views/Forms/EventForm/MigrateForwardButton.tsx, packages/web/src/views/Forms/EventForm/types.ts, packages/web/src/views/Forms/SomedayEventForm/SomedayEventForm.test.tsx, packages/web/src/views/Forms/SomedayEventForm/SomedayEventForm.tsx
Closes https://github.com/SwitchbackTech/compass/issues/525
The new buttons behave the same as they do in the someday event rectangle.
=> ✨ Feat: add migrate buttons to someday event form

packages/backend/.env.example, packages/backend/package.json, packages/backend/src/app.ts, packages/backend/src/common/constants/env.constants.ts, packages/backend/src/common/services/gcal/gcal.service.ts, packages/backend/src/servers/ngrok/ngrok.server.ts, packages/backend/src/servers/ngrok/ngrok.utils.ts, packages/backend/src/sync/util/sync.util.ts, yarn.lock
This PR integrates ngrok for local development so that the gcal watch events can be subscribed to and tested locally.
closes #593
=> Feat integrate ngrok

packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEventContainer/SomedayEventContainer.test.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEventContainer/SomedayEventContainer.tsx
Closes https://github.com/SwitchbackTech/compass/issues/536
https://github.com/user-attachments/assets/7be49ee4-4258-4a18-b107-08557b50d131
=> ✨ Feat(web): Add migrate forward/backward functionality if a someday event is focused

packages/web/src/common/types/web.event.types.ts, packages/web/src/views/Calendar/components/Draft/sidebar/hooks/useSidebarActions.ts
Closes https://github.com/SwitchbackTech/compass/issues/583
=> 🐛 Fix(web): invalid type errors when creating someday event

package.json, packages/backend/.env.example, packages/backend/src/app.ts, packages/core/src/constants/core.constants.ts
Adds support for the updated deployment workflow
Close #630
=> Refactor support unified deployment workflow

packages/web/src/views/Forms/EventForm/EventForm.test.tsx
Closes https://github.com/SwitchbackTech/compass/issues/634
=> fix(web) failing test in EventForm.test.tsx

jest.config.js, packages/backend/.env.example, packages/backend/jest-mongodb-config.js, packages/backend/src/__tests__/backend.test.init.ts, packages/backend/src/__tests__/backend.test.start.ts, packages/core/src/__tests__/core.test.init.ts, packages/core/src/__tests__/core.test.start.ts
This PR adds common test initialization scripts and makes sure only the backend runs a mongo memory server.
Closes #640
=> Refactor jest init

.github/workflows/test.yml, jest.config.js, packages/backend/.env.example, packages/backend/src/app.ts, packages/backend/src/common/constants/env.constants.ts, packages/core/src/__tests__/core.test.init.ts, packages/core/src/__tests__/core.test.start.ts, packages/core/src/util/date/dayjs-compass.plugin.test.ts, packages/core/src/util/date/dayjs-compass.plugin.ts, packages/core/src/util/date/dayjs.ts
This PR add a `dayjs` plugin for the Compass apps
closes #652
=> :sparkles: (dayjs-plugin): add date utilities to dayjs as plugin

packages/web/src/views/Forms/ActionsMenu/ActionsMenu.tsx, packages/web/src/views/Forms/ActionsMenu/MenuItem.tsx, packages/web/src/views/Forms/EventForm/DeleteMenuButton.tsx, packages/web/src/views/Forms/EventForm/DuplicateMenuButton.tsx, packages/web/src/views/Forms/EventForm/EventActionMenu.tsx, packages/web/src/views/Forms/EventForm/MigrateAboveMenuButton.tsx, packages/web/src/views/Forms/EventForm/MigrateBackwardMenuButton.tsx, packages/web/src/views/Forms/EventForm/MigrateBelowMenuButton.tsx, packages/web/src/views/Forms/EventForm/MigrateForwardMenuButton.tsx, packages/web/src/views/Forms/EventForm/MoveToSidebarMenuButton.tsx, packages/web/src/views/Forms/SomedayEventForm/SomedayEventActionMenu.tsx
Closes https://github.com/SwitchbackTech/compass/issues/651
https://github.com/user-attachments/assets/a341957a-d759-4c37-9a1d-39a961035046
=> ✨ feat(web): add keyboard handling to event form menu actions

packages/backend/src/waitlist/controller/waitlist.controller-check.test.ts, packages/backend/src/waitlist/controller/waitlist.controller.ts, packages/backend/src/waitlist/service/waitlist.service.ts
Closes https://github.com/SwitchbackTech/compass/issues/708
=> 🐛 fix(backend): correct user firstName and lastName source

packages/web/src/views/Calendar/components/Draft/hooks/actions/useDraftActions.ts
Closes https://github.com/SwitchbackTech/compass/issues/506
=> 🐛 fix(web): do not call submit if event is not dirty

packages/web/src/ducks/events/slices/someday.slice.ts
Closes https://github.com/SwitchbackTech/compass/issues/720
=> fix(web): Allow adding a someday event even if state is not initialized

packages/web/src/components/Onboarding/OnboardingDemo.tsx, packages/web/src/components/Onboarding/components/Onboarding.tsx
Closes https://github.com/SwitchbackTech/compass/issues/729
=> ✨ Feat: implement arrow navigation in onboarding steps

packages/backend/.env.example
=> 🧹 Chore: Cleanup `.env.example`

packages/web/src/common/utils/position.util.ts, packages/web/src/views/Calendar/components/Grid/Grid.tsx, packages/web/src/views/Calendar/components/Grid/MainGrid/MainGrid.tsx, packages/web/src/views/Calendar/hooks/grid/useDateCalcs.ts, packages/web/src/views/Calendar/hooks/grid/useDragEdgeNavigation.ts
Closes https://github.com/SwitchbackTech/compass/issues/769
=> ✨ feat(web): Transition weeks while holding an event to the edge of the calendar for timed events 

packages/backend/src/__tests__/helpers/mock.setup.ts, packages/backend/src/__tests__/mocks.gcal/factories/gcal.factory.ts, packages/backend/src/common/services/gcal/gcal.service.ts, packages/backend/src/sync/services/import/sync.import.full.test.ts, packages/backend/src/sync/services/import/sync.import.ts, packages/backend/src/sync/services/sync.service.ts
The PR fixes the missing recurring events instances, ensuring all recurring event instances are imported during event sync operations.
closes #797
=> :bug: fix(recurring-events): import all base event instances

packages/backend/src/event/services/event.service.ts
This PR returns a base event's recurrence rule alongside it's instances when fetching events with the follwoing endpoints:
GET `/api/event/:id`
GET `/api/event`
closes #826
=> :sparkles: feat(edit-recurrence): include recurrence rule in fetched instances

packages/web/src/views/Calendar/components/Draft/hooks/effects/useDraftEffects.ts
Closes https://github.com/SwitchbackTech/compass/issues/808
=> fix(web): draft event window closing after socket events change event

packages/web/src/views/Calendar/components/Grid/Grid.tsx, packages/web/src/views/Calendar/components/Grid/MainGrid/EdgeNavigationIndicators/EdgeNavigationIndicators.tsx, packages/web/src/views/Calendar/components/Grid/MainGrid/EdgeNavigationIndicators/index.ts, packages/web/src/views/Calendar/components/Grid/MainGrid/EdgeNavigationIndicators/styled.ts, packages/web/src/views/Calendar/components/Grid/MainGrid/MainGrid.tsx, packages/web/src/views/Calendar/hooks/grid/useDragEdgeNavigation.ts
Closes https://github.com/SwitchbackTech/compass/issues/805
=> ✨ feat(web): UI indication for how and when to transition week when dragging event to week edge

packages/web/src/views/Calendar/components/Draft/sidebar/hooks/useSidebarActions.ts, packages/web/src/views/Calendar/hooks/shortcuts/useShortcuts.ts
Closes https://github.com/SwitchbackTech/compass/issues/903
=> fix: moving event through dnd to calendar edge then drafting someday w/ shortcut not working

packages/web/src/views/Calendar/components/Draft/hooks/actions/useDraftActions.ts, packages/web/src/views/Calendar/components/Draft/sidebar/hooks/useSidebarActions.ts
Closes https://github.com/SwitchbackTech/compass/issues/898
=> 🐛  fix(web): ignore non someday events for sidebar actions, and vice versa.

packages/web/src/views/Calendar/hooks/useWeek.ts
Closes https://github.com/SwitchbackTech/compass/issues/276
=> 🐛 fix(web): someday events between start of month and end of next month not displaying

packages/backend/src/event/classes/compass.event.parser.ts, packages/backend/src/event/services/event.service.test.ts, packages/backend/src/event/services/event.service.ts, packages/backend/src/sync/services/sync/__tests__/compass-sync-processor-this-event/instance.test.ts, packages/core/src/mappers/map.event.test.ts, packages/core/src/mappers/map.event.ts
This PR prevents id changes to base or regular events when they transition to someday events.
closes #986
=> :sparkles: feat(edit-recurrence): keep same id during calendar to someday transition

packages/web/src/views/Calendar/components/Draft/grid/hooks/useGridMouseMove.ts, packages/web/src/views/Calendar/components/Draft/grid/hooks/useGridMouseUp.ts, packages/web/src/views/Calendar/components/Draft/hooks/actions/useDraftActions.ts, packages/web/src/views/Calendar/components/Event/styled.ts, packages/web/src/views/Calendar/components/Grid/AllDayRow/AllDayEvent.tsx, packages/web/src/views/Calendar/components/Grid/AllDayRow/AllDayEvents.tsx
Closes https://github.com/SwitchbackTech/compass/issues/184
=> 🚀  feat(web): implement allday event horizontal duration scaling

packages/web/src/views/Forms/EventForm/DateControlsSection/DateTimeSection/DatePickers/DatePickers.tsx
This PR fixes the bug with changing an all-day event's date from the event form'd date picker.
closes #1009
=> :bug: fix(event-date): fix allday form date change

.github/prompts/issue-creator-zero-shot.prompt.yml
This PR updates the issue creator prompt's test data
=> :sparkles: feat(prompts): update issue creator prompt test data

packages/backend/src/event/services/event.service.ts, packages/core/src/types/calendar.types.test.ts, packages/core/src/types/calendar.types.ts, packages/core/src/types/event.types.ts, packages/core/src/types/type.utils.test.ts, packages/core/src/types/type.utils.ts, packages/web/src/common/types/web.event.types.ts
This PR introduces the `CompassCalendarSchema`.
closes #1063
=> :sparkles feat(sub-calendars): create compass calendar schema

packages/backend/package.json, packages/backend/src/calendar/services/calendar.service.ts, packages/backend/src/common/constants/collections.ts, packages/backend/src/common/services/mongo.service.ts, packages/core/package.json, packages/core/src/__mocks__/v1/calendarlist/gcal.calendarlist.ts, packages/core/src/types/calendar.types.ts, packages/core/src/types/type.utils.test.ts, packages/core/src/types/type.utils.ts, packages/scripts/src/__tests__/integration/2025.10.03T01.19.59.calendar-schema.test.ts, packages/scripts/src/commands/migrate.ts, packages/scripts/src/common/zod-to-mongo-schema.test.ts, packages/scripts/src/common/zod-to-mongo-schema.ts, packages/scripts/src/migrations/2025.10.03T01.19.59.calendar-schema.ts, packages/scripts/src/seeders/2025.10.01T10.09.22.seed-user-events.ts, packages/web/package.json, yarn.lock
This PR creates the `calendar` model alongside its migration script.
closes #1064
=> :sparkles: feat(sub-calendars): create calendar collection and schema
