packages/backend/src/__tests__/event.recur/recur.custom.wip.ts, packages/backend/src/event/queries/event.queries.ts, packages/backend/src/priority/services/priority.service.ts
These outdated calls caused errors, because the code was looking for response keys that were removed in a recent version. This bug surfaced during the mongo update in #73.
closes #74
=> Update Mongo calls for `FindOneAndUpdate` and `FindOneAndReplace`

packages/web/src/views/Calendar/components/Event/Draft/Draft.tsx, packages/web/src/views/Calendar/components/Event/Draft/GridDraft.tsx, packages/web/src/views/Calendar/components/Event/Grid/GridEvent/GridEvent.tsx, packages/web/src/views/Calendar/components/Event/styled.ts
and revert back to default upon resize/drag. before this, the cursor would toggle between the default and row-resize during drag/resize, which was distracting for users.
Closes #117
=> 🐛 Fix(web): make cursor row-resize upon hover

packages/backend/src/auth/controllers/auth.controller.ts, packages/backend/src/auth/services/compass.auth.service.ts, packages/backend/src/common/types/sync.types.ts, packages/backend/src/sync/util/sync.utils.ts, packages/backend/src/user/services/user.service.ts
Address the behavior described in the linked bug in 2 ways:
1. Prevents doing an incremental sync for a user who doesn't have the necessary field (`google.events.nextSyncToken`
2. Removes the step that revokes a user's session when resyncing their google data
Closes #83
=> 🐛 Fix(backend): Improve auth error handling during full-sync response

packages/web/src/__tests__/Calendar/EventForm/eventform.test.tsx, packages/web/src/common/constants/web.constants.ts, packages/web/src/common/utils/event.util.ts, packages/web/src/common/utils/index.ts, packages/web/src/components/Icons/Delete.tsx, packages/web/src/ducks/events/selectors/draft.selectors.ts, packages/web/src/ducks/events/slices/draft.slice.ts, packages/web/src/views/Calendar/Calendar.form.test.tsx, packages/web/src/views/Calendar/Calendar.tsx, packages/web/src/views/Calendar/components/Event/Draft/Draft.tsx, packages/web/src/views/Calendar/components/Event/Grid/GridEvent/GridEvent.tsx, packages/web/src/views/Calendar/components/Event/styled.ts, packages/web/src/views/Calendar/components/Grid/AllDayRow/AllDayEvent.tsx, packages/web/src/views/Calendar/components/Grid/AllDayRow/AllDayEvents.tsx, packages/web/src/views/Calendar/components/Grid/AllDayRow/AllDayRow.tsx, packages/web/src/views/Calendar/components/Grid/MainGrid/MainGrid.tsx, packages/web/src/views/Calendar/components/Grid/MainGrid/MainGridEvents.tsx, packages/web/src/views/Calendar/components/Header/Header.tsx, packages/web/src/views/Calendar/components/LeftSidebar/SomedaySection/SomedayEvents/SomedayEvent.tsx, packages/web/src/views/Calendar/components/LeftSidebar/SomedaySection/SomedayEvents/Wrappers/DraggableSomedayEvent.tsx, packages/web/src/views/Calendar/hooks/draft/sidebar/useSidebar.ts, packages/web/src/views/Calendar/hooks/draft/sidebar/useSidebarEffects.ts, packages/web/src/views/Calendar/hooks/draft/sidebar/useSidebarState.ts, packages/web/src/views/Calendar/hooks/draft/sidebar/useSidebarUtil.ts, packages/web/src/views/Calendar/hooks/draft/useDraftUtil.ts, packages/web/src/views/Calendar/hooks/draft/useGridMouseMove.ts, packages/web/src/views/Calendar/hooks/shortcuts/useShortcuts.ts, packages/web/src/views/CmdPalette/CmdPalette.tsx, packages/web/src/views/Forms/EventForm/EventForm.tsx, packages/web/src/views/Forms/SomedayEventForm/SomedayEventForm.tsx
closes #137 
I added/updated memoization to the `GridEvents` and`AllDayEvents`, so that they only render when necessary. The updates to memoization involved including a custom `arePropsEqual` function, which narrows the props to just look at the event payload and the grid measurements. Previously the memo's shallow equal checks were always failing, because new references were being recreated for the other props
I decoupled state from the `AllDayRow` and `MainGrid`, which was resulting in the grid rendering excessively during edits/drafts. The key strategy here was using the `isEventFormOpen()` and `isEventSomedayFormOpen()` util functions to check whether there was a pending draft occurring. Without these, the all day row, grid, and sidebar were all consuming from a combination of local …
=> ✨ Feat: improve responsiveness during edits

packages/web/src/ducks/events/event.types.ts, packages/web/src/ducks/events/sagas/event.sagas.ts, packages/web/src/views/Calendar/hooks/draft/useDraftUtil.ts
This is a better, non-style-level fix for #178 
As you suggested, I've added some logic into `useDraftUtil.ts:submit` to check if the updated event will be rendered inside current view. If not, it marks the event to be removed from the store after the update. Now once we save an event with dates for a different week, it immediately disapers from the screen.
All automated tests have passed.
However, the "flicking" event with full width still persists for some milliseconds once you change weeks. I'm not sure yet what is the cause of this, but I will let the PR open while I give a look on this.
=> 🐛 Fix: All day event doesn't disappear after changing the week - Attempt #2

packages/web/src/common/utils/web.date.util.test.ts, packages/web/src/common/utils/web.date.util.ts, packages/web/src/views/Calendar/components/Header/Header.tsx
This resolves issue #165 
What I've done:
- Created a `getCalendarHeadingLabel` util function for `Header.tsx`.
- Refactored `getWeekRangeLabel` util function so it can return two different formats.
- Added a `web.date.util.test.ts` file, containing unit tests for `getWeekRangeLabel` and `getCalendarHeadingLabel`.
- Left `getMonthListLabel` unmodified, as it already behaves as expected (returns the full month name of week start).
I didn't write unit tests for `getMonthListLabel` due to its simplicity, but I can add it if you see it as necessary.
All unit tests (including the added ones) have passed.
=> ♻️ refactor: make header labels more accurate

packages/core/src/types/event.types.ts, packages/web/src/common/constants/web.constants.ts, packages/web/src/common/types/web.event.types.ts, packages/web/src/common/utils/event.util.ts, packages/web/src/ducks/events/event.types.ts, packages/web/src/ducks/events/sagas/event.saga.util.ts, packages/web/src/ducks/events/sagas/event.sagas.ts, packages/web/src/ducks/events/slices/event.slice.ts, packages/web/src/ducks/events/slices/someday.slice.ts, packages/web/src/ducks/events/slices/week.slice.ts, packages/web/tsconfig.json
Fixes [this](https://github.com/SwitchbackTech/compass/issues/145)
Uses an optimistic UI rendering approach.
I believe Optimistic UI approach is the simplest and easiest solution under the current circumstances.
There are a couple of edge cases that needs to be handled that I believed were out of scope of this issue, but should be tackled in the future; during the timespan where the optimistically generated event is created and the HTTP request returns a response from the server:
- The event cannot be drag and dropped
- The event cannot be deleted (would delete a local version but the API would re-generate a new one after the HTTP request returns a response)
We can tackle these separately
=> 🐛 fix: keep new event on grid during save

packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEvent.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/Wrappers/DraggableSomedayEvent.tsx
Fixes [issue](https://github.com/SwitchbackTech/compass/issues/190)
This appears to be a react-beautiful-dnd issue due to the `onDragEnd` event not being called immediately on mouseup
Upon further investigation the root cause was due to its drop animation behavior causing a delay to the `onDragEnd` event
For more info, see: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/drop-animation.md#skipping-the-drop-animation
Right now, the event renders with the correct date and time, but only renders after the http request returns a response
I handled optimistically inserting the to-be-rendered event, which is why I rebased this branch off of `that-one-arab:bug_keep_new_event_on_grid_during_save` in [here](https://github.com/SwitchbackTech/compass/pull/197) since it has …
=> 🐛 fix(web): Event saved with wrong time when drag and dropping from sidebar

packages/web/src/common/styles/theme.util.ts, packages/web/src/views/Calendar/components/Event/Grid/GridEvent/GridEvent.tsx, packages/web/src/views/Calendar/components/Event/styled.ts
While you already proposed a solution for this issue [here](https://github.com/SwitchbackTech/compass/issues/201#issue-2758833319), preventing the user from initially DnD or editing the event did not seem very UI/UX friendly to me.
I thought about and researched other solutions, the best solution to handle this issue is to implement **Transactional State Management** to handle this type of transient data, but this implementation itself is split into many strategies.
Each strategy has its own pros and cons, but they all share 1 same con and that is they are difficult to implement and adds lots of overhead.
The 2nd best approach was to simply display a loading indication when the event is initially being created, removing the optimistic approach entirely.
But this would:
- Undo some of the …
=> 🐛 Fix: Disable newly created event from being editing during optimistic render cycle

packages/backend/src/common/constants/collections.ts, packages/backend/src/common/constants/env.constants.ts
Follow-up fix to a bug that was introduced in #208 
This was previously using the old path, which resulted in collections always falling back to their default (prod) values, rather than using the expected values in dev
=> 🐛 fix(backend): use updated IS_DEV value when creating Collections

packages/backend/package.json, packages/scripts/src/cli.ts, packages/scripts/src/cli.validator.ts, packages/scripts/src/commands/build.ts, packages/scripts/src/common/cli.types.ts, packages/scripts/src/common/cli.utils.ts
This pull request includes significant refactoring and improvements to the CLI tools, including the introduction of a new `CliValidator` class, enhancements to the build and delete commands, and the addition of the `zod` library for schema validation. The most important changes are summarized below:
* **Introduction of `CliValidator` class**: Added a new `CliValidator` class to handle CLI option validation and error handling, replacing inline validation logic. (`packages/scripts/src/cli.validator.ts`)
* **Refactor of `cli.ts`**: Refactored the CLI script to use the new `CliValidator` class and encapsulated CLI logic within a `CompassCli` class for better modularity and maintainability. (`packages/scripts/src/cli.ts`)
* **Improved build command**: Modified the `runBuild` function and …
=> 🏗 build(cli): extract args before running build cmd

packages/backend/src/event/queries/event.queries.ts
Should fix [issue](https://github.com/SwitchbackTech/compass/issues/207)
After attempting to reproduce the issue and following the trail, I realized the error mentioned in the issue is occurring whenever an event is unlinked from a user (a `user` property, that represents the user id, does not exist in the mongodb event document)
the `user` property is unlinked whenever we overwrite the event without a `user` property.
This happens because we rely on frontend request body event payload containing a `user` property, but as explained below there are instances when its not provided.
Update Event API relies on providing event id and user id to MongoDB API in order to update an event. The frontend provides the event object which contains the event id and the user id.
The issues are:
- When …
=> 🐛 Fix: Ensure backend service provides user id when updating an event

packages/web/src/common/utils/index.ts, packages/web/src/views/Calendar/hooks/grid/useDateCalcs.ts
This is a proactive fix that I did while working on [210](https://github.com/SwitchbackTech/compass/issues/210)
This does not fix 210. I felt the need to work on it because:
- I saw an opportunity for UX enhancement
- Fixing it will strengthen my understanding of the codebase (events and draft events time calculation)
I will continue work on 210 and ship a fix for it in the next PR
Here's a before and after:
[draft_event_ux_enhancement_before.webm](https://github.com/user-attachments/assets/1e890e87-89d8-4ab9-8953-2bf9e22785e1)
**You can notice that even though the click was outside the 8am timeframe, it counted towards 8am**
[draft_event_ux_enhancement_after.webm](https://github.com/user-attachments/assets/34e70148-1161-4958-95ab-51521b802ede)
The click now accurately counts towards 7:45 …
=> 🐛 Fix:(web): Enhance UX for draft event start date time calculation on mousedown

packages/web/src/common/types/util.types.ts, packages/web/src/views/Calendar/Calendar.tsx, packages/web/src/views/Calendar/components/Event/Grid/GridEventPreview/GridEventPreview.tsx, packages/web/src/views/Calendar/components/Event/Grid/GridEventPreview/snap.grid.test.ts, packages/web/src/views/Calendar/components/Event/Grid/GridEventPreview/snap.grid.ts, packages/web/src/views/Calendar/components/Event/Grid/GridEventPreview/styled.ts, packages/web/src/views/Calendar/components/Sidebar/Sidebar.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/MonthSection/MonthSection.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEvents.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayTab.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/WeekSection/WeekSection.tsx, packages/web/src/views/Calendar/hooks/draft/sidebar/useSidebarUtil.ts, packages/web/src/views/Calendar/hooks/draft/useMousePosition.ts
Fixes [issue](https://github.com/SwitchbackTech/compass/issues/210)
This PR handles implementing more accurate snapping when dragging someday events to the grid.
The issue the PR addresses happens due to a calculation mismatch between 2 methods: `GridEventPreview:getTimePreview()` and `GridEventPreview/styled:getItemStyles()`. This is due to the methods relying on different calculation variables, producing different results in certain mouse movement edge cases.
The PR fixes that by matching the calculation logic inside the `getItemStyles` method with the `getTimePreview` method (it does not do it directly, because as a small refactor, we extracted snapping logic from `getItemStyles` inside its dedicated `snapToGrid` function. See `snapToGrid`)
To achieve that, we needed to feed …
=> 🐛 Fix: Implement better snapping when dragging events from sidebar to grid

packages/web/src/views/Calendar/components/Sidebar/styled.ts, packages/web/src/views/Forms/EventForm/styled.ts
This pull request addresses #142 and includes changes to the `packages/web/src/views/Calendar/components/Sidebar/styled.ts` and `packages/web/src/views/Forms/EventForm/styled.ts` files. The changes focus on updating the styling and component usage within these files.
Styling and component updates:
* [`packages/web/src/views/Calendar/components/Sidebar/styled.ts`](diffhunk://#diff-9ec2728937642a617e7865dacbb4becdac60f3d46072bac5a2e3e7ddc91e80e2L73-R73): Changed the width of the `SidebarTabContainer` from 100% to a fixed width defined by `SIDEBAR_OPEN_WIDTH`.
* [`packages/web/src/views/Forms/EventForm/styled.ts`](diffhunk://#diff-72d2ad197368c949bb555de867e062cbcf20c77ea38a3f01a66c7b6749d4b8deR8): Added an import for the `Input` component from `@web/components/Input`.
* …
=> 🐛 Fix(web): Prevent long titles from breaking form length and event widths

packages/web/package.json, packages/web/src/views/Calendar/components/Event/Draft/GridDraft.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEvent.tsx, packages/web/src/views/Forms/hooks/useEventForm.ts, yarn.lock
This pull request closes closes #156 and includes several updates to dependencies and refactors the use of the `useFloating` hook in various components. The most important changes include updating the `@floating-ui/react` dependency, modifying the `useFloating` hook usage in multiple components, and updating the type definitions.
Dependency updates:
* Updated the `@floating-ui/react` dependency from version `^0.19.2` to `^0.27.3` in `packages/web/package.json`.
Refactoring `useFloating` hook usage:
* Modified the `GridDraft` component to use `refs.setReference` and `refs.setFloating` instead of `reference` and `floating` respectively in `packages/web/src/views/Calendar/components/Event/Draft/GridDraft.tsx`. [[1]](diffhunk://#diff-567efd8ebb35a30d0ea840d271f5009a1c6bf0b13883bafc2598433266f5 …
=> 🐛 Fix: Prevent console warning when opening form

packages/web/src/common/types/web.event.types.ts, packages/web/src/common/utils/event.util.test.ts, packages/web/src/common/utils/event.util.ts, packages/web/src/common/utils/grid.util.ts, packages/web/src/ducks/events/selectors/event.selectors.ts, packages/web/src/views/Calendar/components/Grid/MainGrid/MainGridEvents.tsx, packages/web/src/views/Calendar/hooks/event/getPosition.ts
This PR handles detecting and displaying overlapping events so that they're not on top of one another, effectively being hidden and causing bad UX when attempting to view or drag/edit them.
[handle_overlapping_events.webm](https://github.com/user-attachments/assets/5d20983c-eed9-44a2-b3ee-9ae5e4800a5e)
=> ✨ Feat(web): handle overlapping events

packages/web/src/common/constants/web.constants.ts, packages/web/src/common/utils/event.util.test.ts, packages/web/src/common/utils/event.util.ts, packages/web/src/common/utils/position.util.ts, packages/web/src/ducks/events/selectors/event.selectors.ts, packages/web/src/views/Calendar/components/Grid/AllDayRow/AllDayRow.tsx, packages/web/src/views/Calendar/components/Grid/MainGrid/MainGrid.tsx, packages/web/src/views/Calendar/hooks/draft/sidebar/useSidebarUtil.ts, packages/web/src/views/Calendar/hooks/draft/useDraftUtil.ts, packages/web/src/views/Calendar/hooks/shortcuts/useShortcuts.ts
This PR closes #245 by using the correct grid assembly process, which ensures the id is either undefined or an actual string value. We were previously falling back to an empty string
----
This pull request includes several updates and refactoring to the event utilities in the calendar application. The changes aim to improve the handling of event assembly and overlapping event adjustments, as well as update related tests and components.
* Removed `SCHEMA_GRID_EVENT_DEFAULT_POSITION` from `web.constants.ts` and updated related imports accordingly.
* Refactored `assembleGridEvent`, `assembleDefaultEvent`, and `adjustOverlappingEvents` functions in `event.util.ts` to improve event assembly and overlap adjustments. [[1]](diffhunk://#diff-0b8ca0d3429ed8c7fdf27f61eca39c52fd7b9e94cbffc01b16bc98b15 …
=> 🐛 Fix: Get `m` and `m` shortcuts working by using correct grid assembly method

packages/web/src/views/Calendar/components/Event/Grid/GridEvent/GridEvent.tsx, packages/web/src/views/Calendar/components/Event/styled.ts
Closes #248 
The z-index of the text in the event rectangle was preventing the cursor from changing. Increasing the z-index of the scalers fixed thid.
----
This pull request includes changes to enhance the styling of event scalers in the calendar view by adding a `zIndex` property. The most important changes include modifications to the `ScalerProps` interface and the `StyledEventScaler` component to support the new `zIndex` property.
Styling enhancements:
* [`packages/web/src/views/Calendar/components/Event/Grid/GridEvent/GridEvent.tsx`](diffhunk://#diff-5721933c4be83998cce8f7358189dbf22f9cc59124295b6df4feccd9e6e5d370R124-R131): Added `zIndex` property to the event scalers to ensure proper layering.
* [`packages/web/src/views/Calendar/components/Event/styled.ts`](diffhunk://#diff-f569de75 …
=> 🐛 Fix: Allow cursor change to `row-resize` by using z-index in StyledEventScaler 

packages/web/package.json, packages/web/src/views/Calendar/Calendar.tsx, packages/web/src/views/Calendar/components/Draft/hooks/actions/useDraftActions.ts, packages/web/src/views/Calendar/components/Event/Grid/GridEventPreview/GridEventPreview.tsx, packages/web/src/views/Calendar/components/Grid/Grid.tsx, packages/web/src/views/Calendar/components/Grid/MainGrid/MainGrid.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/MonthSection/MonthSection.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEvents.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/WeekSection/WeekSection.tsx, packages/web/src/views/Calendar/hooks/grid/useDateCalcs.ts, packages/web/src/views/Calendar/hooks/grid/useDragEventSmartScroll.ts, packages/web/src/views/Calendar/hooks/grid/useGridLayout.ts, packages/web/src/views/Calendar/hooks/grid/useScroll.ts, yarn.lock
Closes [issue](https://github.com/SwitchbackTech/compass/issues/241)
This PR implements an auto scroll feature to auto scroll the user when they drag an event to the bottom or top edge of the main grid area.
It handled refactoring parts of the code along the way, mainly removing `gridScrollRef` to simplify the code.
It also handled fixing a bug caused by an edge case that was always present, but became more apparent with this new feature. The bug is: when dragging an event to the very bottom of the screen, you can place the event in a way that the end date would overflow outside the bottom edge of the main grid area container. Details in below video:
- Feature: Implement auto scroll when user drags an event to the bottom/top of the main grid
- Chore: Remove `gridScrollRef`
- handle edge …
=> ✨ Feat: Auto scroll when dragging

.github/ISSUE_TEMPLATE/1-feature-request.yml
The issue itself requires a title, so this field is redundant and just slows the process down. Snip snip ✂️
=> 📜 Docs: Remove Feature Title Input from Issue Template

eslint.config.mjs
This corrects a syntax error in the eslint config which was causing Eslint to crash. 
Follow-up to #269. Related to #271, #149, and #257. 
Replaced direct plugin usage in eslint config with plugin object.
The flat config system expects each item in the array to be a valid configuration object Plugins need to be explicitly registered in the plugins field
```
[Error - 6:55:34 AM] ConfigError: Config (unnamed): Unexpected key "meta" found.
at rethrowConfigError (/Users/tyler/src/switchback/compass/node_modules/@eslint/config-array/dist/cjs/index.cjs:328:8)
at /Users/tyler/src/switchback/compass/node_modules/@eslint/config-array/dist/cjs/index.cjs:1174:5
at Array.reduce (<anonymous>)
at FlatConfigArray.getConfigWithStatus (/Users/tyler/src/switchback/compass/node_modules/@eslint/config-array/d …
```
=> 🐛: Fix ESLint configuration for Prettier plugin

packages/web/src/views/Forms/EventForm/DateTimeSection/TimePicker/TimePickers.tsx
Fixes #263 
https://github.com/user-attachments/assets/2179c3aa-fb96-4600-9aa5-73d3b32203dc
https://github.com/user-attachments/assets/de0892d4-ba56-4e1f-bdfb-6c1a43822aeb
Apologies for not following the contribution guidelines. I did not see them initially and just wanted to take a look at this issue.
=> 🐛 Fix: Time pickers returning wrong value when defaulted

packages/web/src/common/utils/draft/draft.util.test.ts, packages/web/src/common/utils/draft/draft.util.ts, packages/web/src/common/utils/draft/someday.draft.util.ts, packages/web/src/common/utils/event.util.ts, packages/web/src/views/Calendar/hooks/shortcuts/useShortcuts.ts, packages/web/src/views/CmdPalette/CmdPalette.tsx
closes #274 
https://github.com/user-attachments/assets/2195dd1e-b342-4c98-a0fe-bf3f9866cb0c
Introduces a known bug: #283
=> 🐛 Fix: Cmd Palette not triggering new events

packages/web/src/App.tsx, packages/web/src/components/IconProvider/IconProvider.tsx, packages/web/src/components/Icons/styled.ts, packages/web/src/views/Calendar/components/Dedication/Dedication.tsx, packages/web/src/views/Calendar/components/Header/Header.tsx, packages/web/src/views/Calendar/components/Sidebar/Sidebar.tsx, packages/web/src/views/Calendar/components/Sidebar/SidebarIconRow/SidebarIconRow.tsx, packages/web/src/views/Forms/EventForm/DateTimeSection/DatePickers/DatePickers.tsx, packages/web/src/views/Forms/EventForm/DateTimeSection/DateTimeSection.tsx
Closes #284 
This pull request introduces several changes to the `packages/web` project, focusing on the addition of an `IconProvider` component, refactoring of icon-related code, and minor improvements to the event form's date pickers.
* Added a new `IconProvider` component to manage icon context and size (`packages/web/src/components/IconProvider/IconProvider.tsx`).
* Wrapped `RootRouter` with `IconProvider` in the `App` component (`packages/web/src/App.tsx`). [[1]](diffhunk://#diff-d69beff79a8cb8294bbc8ed0f7ccb984740a825ec44db4cc0a5a7b30966ab647R17) [[2]](diffhunk://#diff-d69beff79a8cb8294bbc8ed0f7ccb984740a825ec44db4cc0a5a7b30966ab647R43-R45)
* Simplified `iconStyles` by removing the `isFocused` prop and using `IconProps` instead (`packages/web/src/components/Icons/styled.ts`).
* …
=> 🐛 Fix: isFocused devtools warning

packages/web/src/views/Calendar/hooks/grid/useGridEventMouseDown.ts
Closes https://github.com/SwitchbackTech/compass/issues/298
I'm not sure why we have the below removed piece of code, but it was the culprit behind the issue.
I read the code comments about allowing drag only if form is open, but I couldn't comprehend it.
If it was part of an important UX logic we can revisit this in the future
[Peek.webm](https://github.com/user-attachments/assets/6c5bd296-a940-42a8-8206-391058a5bbb7)
[Peek.webm](https://github.com/user-attachments/assets/65424633-4353-45a4-b7ad-cee010c762ed)
=> 🐛 Fix: dragging an event with its form window open does not work

packages/web/src/views/Calendar/hooks/grid/useDragEventSmartScroll.ts
Fixes https://github.com/SwitchbackTech/compass/issues/266
It's a pretty straightforward fix. We just needed to let the `useEffect` know when we stopped dragging so it can stop auto scrolling accordingly.
[Peek 2025-03-15 11-04.webm](https://github.com/user-attachments/assets/4a6b3641-988d-4159-a824-1ea7fcbc1c4e)
[Peek.webm](https://github.com/user-attachments/assets/95fc372b-5338-4f99-b6ff-5df44156871b)
=> fix(web): Grid scrolls indefinitely when user drags event down

packages/core/src/util/app.util.ts, packages/web/src/views/Calendar/components/Draft/hooks/actions/useDraftActions.ts, packages/web/src/views/Calendar/hooks/grid/useDateCalcs.ts
PR originally created in https://github.com/SwitchbackTech/compass/pull/307
Closes https://github.com/SwitchbackTech/compass/issues/266
The culprit was the deleted lines. I tested the deleted changes as thoroughly as possible and detected no noticable UX change. I am confused on why we needed these deleted lines, but as of now I don't see any need for them.
[Peek 2025-03-17 21-16.webm](https://github.com/user-attachments/assets/383d1209-094d-42d9-b5a8-092aa6b1fdca)
[Peek.webm](https://github.com/user-attachments/assets/8451ec52-effc-493b-a918-b01253611361)
=> 🐛 Fix: set right duration when dragging up outside maingrid view

packages/web/src/components/ContextMenu/GridContextMenuWrapper.tsx
Closes https://github.com/SwitchbackTech/compass/issues/334
When right clicking on an all day event then clicking edit, the all day events creates a copy of itself in the bottom relative to where the edit click occurred.
This issue occurs due to us not providing the incorrect event type when creating a draft in the global store. Statically providing a timed event category type means that the draft will always render in the timed events grid area rather than the all day grid area.
[Peek 2025-04-01.webm](https://github.com/user-attachments/assets/de988432-0fab-4d55-993f-dd58fd906301)
[Peek 2025-04-01.webm](https://github.com/user-attachments/assets/fcbb422a-8e58-4748-b169-a81dc9025fa5)
=> 🐛 Fix: editing all day event using context menu creates duplicate event in UI

packages/web/src/views/Calendar/components/Draft/grid/GridDraft.tsx, packages/web/src/views/Calendar/components/Draft/hooks/actions/useDraftActions.ts, packages/web/src/views/Calendar/components/Draft/hooks/state/useDraftState.ts
Closes https://github.com/SwitchbackTech/compass/issues/303
When dragging an event with its form window open, the form window does not re-open after we finish dragging.
This PR addresses this issue by re-opening the form window if it was previously open
https://github.com/user-attachments/assets/655ee7b6-3753-498a-abe5-19a1b325a657
https://github.com/user-attachments/assets/7dbb6f0a-d9d5-4b72-9654-26b63a569a66
=> ✨ Feat:  event window not reopening 

packages/web/src/common/utils/device.util.ts, packages/web/src/components/Tooltip/Tooltip.tsx, packages/web/src/components/Tooltip/TooltipWrapper.tsx, packages/web/src/views/Calendar/Calendar.form.test.tsx, packages/web/src/views/Calendar/components/Draft/grid/GridDraft.tsx, packages/web/src/views/Forms/EventForm/DeleteButton.tsx, packages/web/src/views/Forms/EventForm/EventForm.test.tsx, packages/web/src/views/Forms/EventForm/EventForm.tsx, packages/web/src/views/Forms/EventForm/MoveToSidebarButton.tsx, packages/web/src/views/Forms/SomedayEventForm/SomedayEventForm.tsx
Closes https://github.com/SwitchbackTech/compass/issues/183
This PR mainly implements the following
- Tooltips for the event form's delete button and move to sidebar button
- Shortcut for the event form's move to sidebar button (META + shift + <)
=> ✨ Feat: EventForm better shortcuts and tooltips

packages/backend/src/__tests__/backend.test.start.js, packages/backend/src/__tests__/helpers/mock.db.queries.ts, packages/backend/src/__tests__/mocks.ccal/ccal.event.factory.ts, packages/backend/src/__tests__/mocks.ccal/ccal.mock.db.util.ts, packages/backend/src/__tests__/mocks.gcal/factories/gcal.factory.ts, packages/backend/src/event/queries/event.queries.ts, packages/backend/src/event/queries/event.recur.queries.ts, packages/backend/src/event/services/event.service.ts, packages/backend/src/event/services/recur/util/recur.gcal.util.ts, packages/backend/src/sync/services/import/all/import.all.gcal.ts, packages/backend/src/sync/services/import/all/import.all.util.ts, packages/backend/src/sync/services/import/sync.import.test.ts, packages/backend/src/sync/services/import/sync.import.ts, packages/backend/src/sync/services/import/sync.import.types.ts, packages/backend/src/sync/services/notify/handler/gcal.notification.handler.ts, packages/backend/src/sync/services/sync/gcal.sync.processor.test.ts, packages/backend/src/sync/services/sync/gcal.sync.processor.ts, packages/backend/src/sync/sync.types.ts
Closes #346 
Fixes duplicate event bug by differentiating between base and instance recurrences
Refactors import code
1. Moves paginated fetching into separate file
2. names `CANCELLED` to `DELETED` in `Operation_Sync` type for accuracy
Organizes code
1. Extracts queries related to recurring events to separate file
Updates Tests
1. improves mock gcal list mocking by supporting pagination
=> 🐛 Fix(backend): Prevent duplicates during full import

packages/backend/src/auth/controllers/auth.controller.test.ts, packages/backend/src/auth/controllers/auth.controller.ts, packages/backend/src/sync/services/import/sync.import.ts
Closes #308 
This PR resyncs user data if their sync token couldn't be found during login
----
This pull request introduces several changes to improve the handling of Google synchronization errors and adds comprehensive tests for the `AuthController`. The most important changes include the addition of tests for the `login` method, handling `NoSyncToken` errors during incremental sync, and updating error handling in the `SyncImport` service.
* [`packages/backend/src/auth/controllers/auth.controller.test.ts`](diffhunk://#diff-138135e8ca28da77f66301292f489e602806936c0543fba4926ca73e0734827cR1-R68): Added unit tests for the `login` method in `AuthController`, including mocks for dependencies and a test case to handle the `NoSyncToken` error.
* …
=> ✨ Feat: Resync user data if sync token not found during login

packages/backend/src/__tests__/helpers/mock.events.init.ts, packages/backend/src/__tests__/mocks.gcal/factories/gcal.event.factory.set.ts, packages/backend/src/__tests__/mocks.gcal/factories/gcal.event.factory.test.ts, packages/backend/src/__tests__/mocks.gcal/factories/gcal.event.factory.ts, packages/backend/src/__tests__/mocks.gcal/mocks.gcal/factories/gcal.event.factory.ts, packages/backend/src/common/services/gcal/gcal.utils.ts, packages/backend/src/event/services/event.find.test.ts, packages/backend/src/event/services/event.service.ts, packages/backend/src/event/services/event.service.util.ts, packages/backend/src/event/services/recur/parse/recur.gcal.parse.ts, packages/backend/src/event/services/recur/queries/event.recur.queries.ts, packages/backend/src/event/services/recur/util/recur.util.ts, packages/backend/src/sync/services/import/all/import.all.util.ts, packages/backend/src/sync/services/import/sync.import.full.test.ts, packages/backend/src/sync/services/import/sync.import.series.test.ts, packages/backend/src/sync/services/import/sync.import.test.ts, packages/backend/src/sync/services/import/sync.import.ts, packages/backend/src/sync/services/import/sync.import.types.ts, packages/backend/src/sync/services/import/sync.import.util.ts, packages/backend/src/sync/services/sync/gcal.sync.processor.test.ts, packages/backend/src/sync/services/sync/gcal.sync.processor.test.util.ts, packages/backend/src/sync/services/sync/gcal.sync.processor.ts, packages/core/src/mappers/map.event.test.ts, packages/core/src/types/event.types.ts, packages/core/src/types/gcal.d.ts, packages/core/src/util/event.util.ts
Closes #358 
Create a new base and instances after receiving a notification from gcal with a new base event
- Updates import logic to allow the first instance to be imported
- Filters out the base event when returning data in the GET
- The above two changes allow us to have access to the `recurrence` rule, without needing to duplicate the base recurrence on the first instance in the UI
Convenience changes:
- Adds date util for filtering event categories
Status of the recurring event read-only feature:
✅ DELETE ALL
✅ DELETE ONE
✅ UPDATE ONE
✅ DELETE THIS AND FOLLOWING
✅ CREATE ALL (this PR)
❌ UPDATE ALL (future PR)
❌ UPDATE THIS AND FOLLOWING (future PR)
=> ✨ Feat: Add support for syncing recurring event CREATE (readonly)

packages/web/src/views/Calendar/components/Draft/hooks/actions/useDraftActions.ts
Closes https://github.com/SwitchbackTech/compass/issues/364
Stemmed from 0b47a5cf0dd302798a4c6bcbd24f8f0d2b84edb7 Where we forgot to check for all day events, since we don't handle any drag offset for all day events.
=> fix(web): Runtime error when dragging an all day event

packages/web/src/views/Calendar/components/Draft/grid/GridDraft.tsx, packages/web/src/views/Calendar/components/Draft/hooks/actions/useDraftActions.ts
Closes https://github.com/SwitchbackTech/compass/issues/357
When mousing down on a new draft, the duration is reset instead of being preserved.
This bug was introduced in https://github.com/SwitchbackTech/compass/pull/361
This PR resolves this issue, by preserving the duration and adding support for maintaining cursor position for draft events
https://github.com/user-attachments/assets/f2ca0fbb-4424-41c9-b054-5f800b115eb6
https://github.com/user-attachments/assets/72c6f52f-389d-4885-a8b7-24a6fc69c5c0
=> 🐛 Fix: Draft event duration not preserved when mousing down

packages/web/src/views/Forms/EventForm/EventForm.test.tsx, packages/web/src/views/Forms/EventForm/EventForm.tsx, packages/web/src/views/Forms/EventForm/MoveToSidebarButton.tsx
Closes https://github.com/SwitchbackTech/compass/issues/350
the current hotkey combination did not work. This new combination is simpler and guaranteed to work (for english keyboard layouts)
=> fix(web): replace move to sidebar shortcut hotkey

packages/backend/src/common/constants/error.constants.ts, packages/backend/src/sync/controllers/sync.controller.ts
Logs instead message instead of full error to signify that this is a known scenario and not something we need to do anything about
Closes #379
=> 🐛 Fix: Handle NoSyncToken error during gcal notification

packages/web/src/views/Forms/EventForm/EventForm.test.tsx, packages/web/src/views/Forms/EventForm/EventForm.tsx, packages/web/src/views/Forms/EventForm/MoveToSidebarButton.tsx
Closes #350 by making the shortcut `META + SHIFT + COMMA` AKA `META + SHIFT + 
English keyboards have the `<` and the `,` on the same key, so this is also effectively  `META + <` for those users.
=> 🐛 Fix: replace move to sidebar shortcut hotkey. Attempt 2

packages/web/src/common/store/helpers/index.ts, packages/web/src/ducks/events/context/sync.context.ts, packages/web/src/ducks/events/context/week.context.ts, packages/web/src/ducks/events/event.types.ts, packages/web/src/ducks/events/selectors/sync.selector.ts, packages/web/src/ducks/events/selectors/util.selectors.ts, packages/web/src/ducks/events/slices/sync.slice.ts, packages/web/src/socket/SocketProvider.tsx, packages/web/src/views/Calendar/components/Grid/AllDayRow/AllDayEvents.tsx, packages/web/src/views/Calendar/components/Grid/MainGrid/MainGridEvents.tsx, packages/web/src/views/Calendar/hooks/useRefresh.ts, packages/web/src/views/Calendar/hooks/useWeek.ts
Closes https://github.com/SwitchbackTech/compass/issues/384
This fix implements a lot of boilerplate code, but it can be easily summed up this way:
- The root issue is: when we re-fetch the events, we stop rendering them `MainGridEvents:84` and `AllDayEvents:59` until we finish re-fetching
- This causes the events "flashing" in the UI
- If we remove this condition (rendering only when we don't have an active request condition), we re-produce https://github.com/SwitchbackTech/compass/issues/186
- That is why we need some way to know **why** we are refetching, so that we can decide whether to continuously render the events or pause rendering them when a request is in flight
- The rest is boilerplate code that implements the **why** part, setting up a context object (for scalability) and …
=> 🐛 Fix: fetch events when receiving re-fetch request from socket without flashing them in the UI

packages/web/src/components/LoginAbsoluteOverflowLoader/LoginAbsoluteOverflowLoader.tsx, packages/web/src/components/LoginAbsoluteOverflowLoader/styled.ts, packages/web/src/views/Login/Login.tsx
Closes https://github.com/SwitchbackTech/compass/issues/391
When user signs up to platform, they are prompted to log in with google, this helps authenticates them and migrates their google calendar events to our platform (if any exist)
If they have a lot of google calendar events, migration can take too long, meaning the signup process will take too long.
This PR implements dynamic loading messages to let the user know the signup may take a while and to reassure the user  everything is OK
https://github.com/user-attachments/assets/906a1ae0-771a-4d4a-b5fe-dfc9cbeddff5
=> feat(web): Implement dynamic loading messages when signing up takes too long

packages/web/src/views/Calendar/hooks/shortcuts/useShortcuts.ts
Closes https://github.com/SwitchbackTech/compass/issues/245
Fix: Enable M and W shortcuts even when sidebar is closed
=> Fix: Enable M and W shortcuts even when sidebar is closed

packages/web/src/views/Forms/EventForm/SaveSection/SaveSection.tsx
Closes https://github.com/SwitchbackTech/compass/issues/416
https://github.com/user-attachments/assets/000bee1e-156d-4fa5-9736-e701ea1858fe
https://github.com/user-attachments/assets/d37830b5-319f-4290-92cf-c6264ef15d0d
=> 🐛 Fix: Saving an event creates 2 events rather than 1

packages/backend/src/sync/services/import/all/import.all.gcal.ts, packages/backend/src/user/services/user.service.ts
Closes #423 by adding log statements during sign up. We can improve this in the future by tracking these in a centralized place, but this is good enough for now.
Also slightly improves performance by increasing the max event size from 500 to 1000.
**User 1: 36k events**
Some examples:
36500 events @ 500 events / request = 42 seconds
```
167|backend  | 25-05-16 13:01:11 [info] sync.import.all.gcal: Pass 2 completed for <user>
167|backend  |     Processed Gcal events: 36503
167|backend  |     Saved Compass events: 36503
167|backend  |     Duration: 42.61s
167|backend  |
```
36500 events @ 1000 events / request= 36s
```
168|backend  | 25-05-16 13:07:11 [info] sync.import.all.gcal: Pass 2 completed for <user>
168|backend  |     Processed Gcal events: 36503
168|backend  |     Saved Compass …
```
=> ✨ Feat: Add Duration log during event import

packages/web/src/common/utils/event.util.ts, packages/web/src/components/ContextMenu/ContextMenuItems.tsx, packages/web/src/components/ContextMenu/GridContextMenuWrapper.tsx, packages/web/src/views/Calendar/Calendar.tsx, packages/web/src/views/Calendar/components/Draft/sidebar/context/useSidebarContext.ts, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEvent/SomedayEvent.tsx, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEventContainer/SomedayEventContainer.tsx
Closes https://github.com/SwitchbackTech/compass/issues/426
Closes https://github.com/SwitchbackTech/compass/issues/427
Support displaying custom context menu items for someday events, allowing someday events to utilize the same menu items which act as shortcuts to certain event actions.
Reason why we addressed 2 issues in the same PR is because the 2 issues are very closely related in terms of code implementation so it would have been counter intuitive to create separate PRs for them.
https://github.com/user-attachments/assets/04ba348c-0f26-4764-8819-424c78796ef0
=> ✨ Feat: Support custom context menu for someday events

packages/backend/src/common/errors/generic/generic.errors.ts, packages/backend/src/common/errors/handlers/error.express.handler.ts, packages/backend/src/common/errors/handlers/error.handler.ts, packages/backend/src/sync/controllers/sync.controller.ts, packages/backend/src/sync/services/import/sync.import.ts
- correct typos in backend error messages
- `yarn test` *(fails: could not download yarn)*
- `yarn run "lint -f"` *(fails: could not download yarn)*
=> Fix misspellings in backend logs

packages/web/src/views/Forms/EventForm/EventForm.test.tsx, packages/web/src/views/Forms/EventForm/EventForm.tsx
Problem
- META + d was creating browser bookmarks instead of duplicating events
- CTRL + d was duplicating events (inconsistent with other META shortcuts)
- Browser's default bookmark shortcut (META + d) was interfering with app functionality
Solution
- ✅ Changed duplicate event hotkey from `"ctrl+d"` to `"meta+d"`
- ✅ Existing `preventDefault()` logic stops browser bookmark creation
- ✅ Added comprehensive test coverage for META + d keyboard shortcut
- ✅ Maintains consistency with other META key shortcuts in the app
Testing
- ✅ Unit test verifies META + d calls `onDuplicate` correctly
- ✅ Test confirms no unintended side effects (other functions not called)
- ✅ Existing `handleIgnoredKeys` prevents browser default behavior
Changes
- `packages/web/src/views/Forms/EventForm/EventForm.tsx`: …
=> fix: change duplicate event shortcut from CTRL+d to META+d (#446)

packages/web/src/common/constants/web.constants.ts, packages/web/src/common/utils/index.ts, packages/web/src/components/ContextMenu/ContextMenuItems.tsx, packages/web/src/components/ContextMenu/GridContextMenuWrapper.tsx, packages/web/src/views/Calendar/Calendar.tsx, packages/web/src/views/Calendar/components/Draft/hooks/state/useDraftForm.ts
Closes https://github.com/SwitchbackTech/compass/issues/433
A race condition of sorts was occurring where context menu depends on having a draft event and opening the event form window then clicking on a context menu item would reset the draft event before the context menu action reads its value.
We now check if the context menu is open, and we avoid resetting the draft event accordingly.
=> 🐛 Fix: event form window blocking context menu items

packages/core/src/__mocks__/v1/events/events.misc.ts, packages/web/src/__tests__/Calendar/calendar.render.test.tsx, packages/web/src/__tests__/Calendar/calendar.render.test.utils.ts, packages/web/src/__tests__/__mocks__/server/mock.handlers.ts, packages/web/src/ducks/events/sagas/event.sagas.ts, packages/web/src/ducks/events/sagas/saga.util.ts
Closes https://github.com/SwitchbackTech/compass/issues/428
This hotfix resolves the issue by adjusting start date to be 1 day before the actual start date, this allows us to extend our date range to cover additional events that may not be returned. We ensure that the returned events match the initial date range by manually filtering them.
=> 🐛 Fix: Implement hotfix to address events start of week date filter not being returned consistently

packages/core/src/__mocks__/v1/events/events.misc.ts, packages/web/src/__tests__/Calendar/calendar.render.test.tsx, packages/web/src/__tests__/Calendar/calendar.render.test.utils.ts, packages/web/src/__tests__/__mocks__/mock.render.tsx, packages/web/src/__tests__/__mocks__/state/state.weekEvents.ts
Fix: Calendar Timed Event Test Reliability (calendar.render.test.tsx)
- The test Calendar: Display with State > displays timed events was intermittently failing. The root cause was that the test utility freshenEventStartEndDate set the event date to a relative range that did not always align with the current calendar view, causing the "groceries" event to be filtered out and not rendered.
- Updated freshenEventStartEndDate:
- This utility now sets the test event’s start and end date to the current week’s Thursday (11am–12pm). This guarantees that the event will always be visible in the main calendar grid during the test, regardless of when the test is run.
Impact
- The test for displaying timed events is now reliable and deterministic.
- No production code was changed; only test utilities …
=> 🧪 Test: fix calendar render test

packages/web/src/common/utils/web.date.util.ts, packages/web/src/views/Calendar/components/Draft/sidebar/hooks/useSidebarActions.ts, packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/DraggableSomedayEvent/DraggableSomedayEvent.tsx, packages/web/src/views/Forms/SomedayEventForm/SomedayEventForm.tsx
Closes https://github.com/SwitchbackTech/compass/issues/527
=> ✨ Feat: move someday event to from week or month section using keyboard shortcuts

packages/web/src/__tests__/__mocks__/state/state.weekEvents.ts, packages/web/src/ducks/events/selectors/view.selectors.ts, packages/web/src/ducks/events/slices/view.slice.ts, packages/web/src/views/Calendar/Calendar.form.test.tsx, packages/web/src/views/Calendar/components/Header/Header.tsx, packages/web/src/views/Calendar/components/Header/HeaderNote/HeaderNote.tsx, packages/web/src/views/Calendar/hooks/shortcuts/useFocusHotkey.ts, packages/web/src/views/CmdPalette/CmdPalette.tsx
This PR adds the  `f` shortcut to edit header note
Closes #420 
https://github.com/user-attachments/assets/020ffe8a-6c0d-45bb-9ba7-c2679acadfb4
=> Feat(add f shortcut to edit header note)

packages/backend/src/auth/controllers/auth.controller.ts, packages/core/src/types/auth.types.ts
Closes #545 by requiring a valid user id before creating a session
=> 🐛 fix: simplify session creation to only use compass user ID

packages/web/src/views/Calendar/components/Sidebar/SidebarIconRow/SidebarIconRow.tsx
- Updated command palette tooltip to show Cmd+K on macOS and Win+K on Windows
- Replace hardcoded 'CMD + K' text with dynamic icons based on user's OS
- Use Command icon for macOS and WindowsLogo icon for Windows users from Phosphor Icons
- Consistent with existing platform-specific shortcuts in the app
I have yet to test on windows.
=> ✨ feat: add platform-specific keyboard shortcuts for cmd palette tooltip

packages/web/src/common/utils/web.date.util.ts, packages/web/src/views/Forms/SomedayEventForm/SomedayEventForm.tsx
=> ✨ Feat(web): Add move to next/prev week/month shortcuts for someday event

packages/web/src/common/utils/shortcut.util.tsx, packages/web/src/views/Calendar/components/Sidebar/SidebarIconRow/SidebarIconRow.tsx, packages/web/src/views/Forms/EventForm/MigrateBackwardButton.tsx, packages/web/src/views/Forms/EventForm/MigrateForwardButton.tsx, packages/web/src/views/Forms/EventForm/MoveToSidebarButton.tsx, packages/web/src/views/Forms/EventForm/SaveSection/SaveSection.tsx
Closes https://github.com/SwitchbackTech/compass/issues/526
Follow up to https://github.com/SwitchbackTech/compass/pull/559
This PR implements shortcut tooltips for the someday event migrate to next/prev week/month.
=> ✨ Feat(web): Implement shortcut tooltips for someday event migrate buttons

packages/web/src/common/utils/draft/someday.draft.util.test.ts, packages/web/src/common/utils/draft/someday.draft.util.ts
Closes https://github.com/SwitchbackTech/compass/issues/569
This was due to use not computing the start-end date correctly when the someday event category is month
https://github.com/user-attachments/assets/7cdb5db2-c679-4572-b2bd-2a419df19496
=> 🐛 Fix: Someday event in wrong location after creating with 'm' shortcut

packages/web/src/views/Forms/EventForm/DuplicateButton.tsx
Closes https://github.com/SwitchbackTech/compass/issues/537
=> 🐛 Fix(web): Duplicate shortcut tooltip using wrong label

packages/web/src/views/Calendar/components/Sidebar/SomedayTab/SomedayEvents/SomedayEvent/styled.ts
Closes https://github.com/SwitchbackTech/compass/issues/535
=> 🐛 Fix(web): incorrect focus color when someday event is dragged using keyboard

packages/core/src/util/date/dayjs.ts
What does this PR do?
This PR adds a customized `dayjs` module for manipulating dates within the Compass app.
closes #608
=> Feat create dayjs module

packages/backend/.env.example, packages/backend/src/__tests__/backend.test.init.ts, packages/backend/src/app.ts, packages/backend/src/common/constants/env.constants.ts
This PR leverages the `TZ` environment variable to set the global timezone for the Compass API. It also sets the default timezone to `UTC` if the environment variable setting is not present.
closes [#625](https://github.com/SwitchbackTech/compass/issues/625)
=> :sparkles: feat(timezone): set timezone and use UTC as default

packages/web/src/views/Forms/EventForm/EventForm.tsx
@that-one-arab  this should be good
Closes https://github.com/SwitchbackTech/compass/issues/584
=> 🐛 Fix(web): added hotkeys to move grid events to sidebar ctrl+meta+left

packages/web/src/views/Calendar/components/Draft/hooks/actions/useDraftActions.ts
Closes https://github.com/SwitchbackTech/compass/issues/623
fix `invalid_type` error when duplicating a someday event due to zod expecting an order field before submission
this provided order field does not impact the UX since logic does not depend on it and the duplicated event calculates the new duplicated event's order field on its own without relying on this provided order field
=> 🐛 Fix(web): invalid_type when duplicating someday event

packages/web/src/components/IconButton/styled.ts
Closes https://github.com/SwitchbackTech/compass/issues/637
=> 🐛 Fix(web):  implement on focus highlight for icon button

packages/backend/src/app.ts, packages/backend/src/servers/ngrok/ngrok.server.ts
This PR ensures that the `ngrok` dynamic module import does not trigger errors during shutdown.
closes #657
=> :bug: fix(shutdown): catch ngrok dynamic import error

packages/scripts/package.json, packages/scripts/src/cli.ts, packages/scripts/src/commands/merge-sync.ts, yarn.lock
This PR dedupes the users's Compass sync data, preventing the mongo db sync queries from failing
closes #662
=> 🔨 feat(dedupe-sync): add cli script to remove duplicate compass user sync

packages/web/src/components/Onboarding/steps/EmailStep.tsx
This pull request makes a small improvement to the onboarding flow by advancing to the next step after successfully checking the waitlist status.
* The `EmailStep` component now calls `onNext()` after retrieving and setting the waitlist status, ensuring the user progresses in the onboarding process.
This was blocking user activity, because the page wasn't responding to the button click.
Closes #678
=> 🐛 Fix (onboarding): Trigger next screen after email

packages/backend/src/event/classes/gcal.event.rrule.test.ts, packages/backend/src/event/classes/gcal.event.rrule.ts, packages/core/src/constants/core.constants.ts, packages/core/src/util/event/gcal.event.util.ts
This PR adds the `GcalEventRRule` parser for parsing rrules in base Google calendar events.
closes #684
=> :sparkles: feat(rrule): add gcal event rrule parser

packages/web/src/views/CmdPalette/CmdPalette.tsx
Closes #675 
This pull request introduces a minor update to the `CmdPalette` component by adding a new external link to Discord. This change enhances user access to community support and engagement.
* Added a "Discord" menu item to the command palette, with an icon and a link to the official Discord server (`CmdPalette.tsx`).
=> ✨ feat(web): add Discord link to command palette

packages/web/src/views/Calendar/components/Event/Grid/GridEvent/GridEvent.tsx
Closes https://github.com/SwitchbackTech/compass/issues/505
=> 🐛 fix(web): prevent resizing event when it is in optimistic state

packages/web/src/components/Onboarding/steps/EmailStep.tsx
Closes https://github.com/SwitchbackTech/compass/issues/706
We display the same "NotOnWaitlist" component for users who are not no the waitlist and on the waitlist, which should not be the casue if the user is on the waitlist but not invited yet.
=> 🐛 fix(web): Handle users who are on waitlist but not invited yet

packages/backend/src/waitlist/controller/waitlist.controller.ts, packages/web/src/components/Onboarding/steps/EmailStep.tsx
Closes https://github.com/SwitchbackTech/compass/issues/701
* Ensure users marked as active are also allowed to proceed to the next step in the onboarding flow.
* Adjust backend to source firstName and lastName from existingUser if not available in waitlistRecord.
=> 🐛 fix(web): update onboarding flow to include active users in waitlist check

package.json, packages/backend/src/__tests__/backend.test.init.ts
This PR initializes the timezone variable within the backend development and test scripts in the `package.json` file.
closes #716
=> :technologist: fix(scripts): set TZ env var in scripts

packages/backend/src/__tests__/helpers/mock.setup.ts, packages/backend/src/__tests__/mocks.gcal/factories/gcal.factory.ts
This PR creates a mock virtual jest module `compass-test-state`, used to store the test state for each test.
The `compass-test-state` module is reset for every test.
closes #689
=> :white_check_mark: test(jest): use ephemeral test states

packages/backend/src/sync/services/import/sync.import.ts, packages/backend/src/sync/util/sync.queries.ts
This PR uses a single mongo transaction and enforces causal consistency when saving the gcal events.
closes #747
=> :sparkles: feat(gcal-import): use single causal txn during import

package.json
This PR allows the child processes spawned within the main backend process to be gracefully terminated, on ts-node-dev initiated reload(due to file changes).
closes #761
=> :sparkles: feat(scripts): send exit signal to child process on reload

packages/backend/src/sync/controllers/sync.controller.test.ts, packages/backend/src/sync/controllers/sync.controller.ts, packages/backend/src/sync/services/import/sync.import.ts, packages/backend/src/sync/services/sync.service.ts, packages/backend/src/sync/util/sync.queries.test.ts, packages/backend/src/sync/util/sync.queries.ts, packages/core/src/types/event.types.ts
This PR cleans up stale sync watches by `channelId` and resolves the `No Sync record - 400` error for existing channels in GCal.
closes #622
=> 🐛 fix(gcal-notifications) cleanup stale sync records

packages/backend/src/__tests__/drivers/waitlist.driver.ts, packages/backend/src/waitlist/controller/waitlist.controller-add.test.ts, packages/backend/src/waitlist/controller/waitlist.controller.ts, packages/backend/src/waitlist/service/waitlist.service.ts, packages/core/src/types/waitlist/waitlist.answer.types.ts, packages/core/src/types/waitlist/waitlist.types.ts
Closes #812 
This PR updates the waitlist schema from version 0 to version 1, simplifying the data structure by removing several boolean and enum fields while adding new optional fields for profession and general feedback.
Key Changes:
- Changed schemaVersion from "0" to "1" in waitlist driver and controller.
- Updated waitlist answer types to include new fields and removed deprecated ones.
- Adjusted tests to reflect changes in the waitlist schema and ensure compatibility with the new version.
- Introduced profession and anythingElse fields in the waitlist data structure.
=> feat(backend): update waitlist schema

.github/ISSUE_TEMPLATE/config.yml
A follow-up to #843 that makes a few more tweaks.
- Added links for Bug Report and Feature Request templates to enhance user guidance.
- Updated Discord community link description for clarity.
- Removed outdated links for Waitlist and Try the App options.
=> 📜 Docs: Improve issue templates

.github/ISSUE_TEMPLATE/config.yml
Another follow-up to #843 
- Removed links for Bug Report and Feature Request templates to streamline the issue creation process.
- Retained the Discord community link for user engagement and support.
=> 📜 Docs: Update issue templates

packages/backend/src/event/classes/compass.event.rrule.test.ts, packages/backend/src/event/classes/compass.event.rrule.ts, packages/core/src/util/date/dayjs-compass.plugin.ts, packages/core/src/util/event/event.util.ts, packages/core/src/util/test/ccal.event.factory.ts
This PR adds an RRule parser for generating recurring Compass events.
closes #817
=> :sparkles: feat(edit-recurrence): add compass rrule parser

packages/backend/src/event/classes/compass.event.generator.ts, packages/backend/src/event/classes/compass.event.parser.test.util.ts, packages/backend/src/sync/services/sync/__tests__/compass-sync-processor-this-event/regular.test.ts, packages/backend/src/sync/services/sync/__tests__/compass.sync.processor.this-and-following-event.test.ts, packages/core/src/mappers/map.event.ts, packages/core/src/util/test/ccal.event.factory.ts
This PR updates the `This and Following Events` recurrence edit logic and add tests for this flow.
closes #928
=> :sparkles: feat(edit-recurrence): update this and ffg events logic

packages/backend/src/auth/controllers/auth.controller.ts
This pull request makes a minor improvement to the `AuthController` by ensuring that the `accessToken` from the newly created session is included in the response when a user session is created. This change helps clients receive the token directly after session creation.
- Added the `accessToken` from `sessionData` to the response object when a user session is successfully created in `auth.controller.ts`.
Closes #941
=> fix(backend): return session data upon user session creation

packages/backend/src/event/controllers/event.controller.ts, packages/backend/src/event/event.routes.config.ts, packages/core/src/types/event.types.ts, packages/web/src/ducks/events/event.api.ts, packages/web/src/views/Onboarding/steps/events/SomedaySandbox/SomedaySandbox.tsx, packages/web/src/views/Onboarding/steps/events/SomedaySandbox/sandbox.util.test.ts, packages/web/src/views/Onboarding/steps/events/SomedaySandbox/sandbox.util.ts
Closes #938 
This pull request introduces support for a new event type, `CompassCoreEvent`, across the backend and frontend, and updates the event creation flow to handle both single and multiple events. It also improves type safety and onboarding instructions. The most important changes are grouped below:
**Backend Enhancements:**
* Added the `CompassCoreEvent` type to the core event types and updated the event controller to accept and process both single and multiple `CompassCoreEvent` objects in the `create` endpoint, improving flexibility for bulk event creation. [[1]](diffhunk://#diff-e1ea1ebfd38ec0378096c1227cb258adfe2b56a5a6800e87ad8bc399ea62b9feR6-L9) [[2]](diffhunk://#diff-e1ea1ebfd38ec0378096c1227cb258adfe2b56a5a6800e87ad8bc399ea62b9feL27-R27) …
=> Fix: create someday events during onboarding

packages/backend/src/event/controllers/event.controller.ts
**Backend fix**
The duplicate functionality was completely broken for both calendar and someday events. When users attempted to duplicate an event via right-click context menu or the Meta+D keyboard shortcut, no new event was created and the UI did not update. This regression was introduced in commit `2de11df` during the recent refactoring of draft actions.
The `duplicateEvent` function in `useDraftActions.ts` was incorrectly passing the original event's `_id` to the submit function:
```typescript
const duplicateEvent = useCallback(() => {
const draft = MapEvent.removeProviderData({
...reduxDraft,
}) as Schema_GridEvent;
submit(draft); // ❌ This includes the original _id
discard();
}, [reduxDraft, submit, discard]);
```
When an event has an existing `_id`, the submit function treats it as …
=> :bug: fix(duplicate-event): fix event duplication - backend

packages/web/src/views/Calendar/components/Grid/AllDayRow/AllDayEvents.tsx
disabled due to a bug reported in https://github.com/SwitchbackTech/compass/issues/184#issuecomment-3344110797
feature temporarily disabled until above bug is addressed
=> hotfix: temporarily disable allday events

packages/web/src/views/Calendar/components/Draft/hooks/actions/useDraftActions.ts, packages/web/src/views/Calendar/components/Grid/AllDayRow/AllDayEvents.tsx
Closes https://github.com/SwitchbackTech/compass/issues/184
=> 🐛  fix: resizing all day events issues

jest.config.js, package.json, packages/scripts/package.json, packages/scripts/src/cli.test.ts, packages/scripts/src/cli.ts, packages/scripts/src/commands/migrate.ts, packages/scripts/src/common/cli.types.ts, packages/scripts/src/common/migrator-template.ts, packages/scripts/src/seeders/2025.10.01T10.09.22.seed-user-events.ts, yarn.lock
This PR adds the ability to generate and run database migrations and seeders to Compass. It updates the Compass cli to support the following commands:
- `yarn cli seed` - existing command updated
- `yarn cli migrate` - new migration command
Run the commands above in your terminal.
you can run the commads with an extra `--help` flag to see the available sub-commands
=> :sparkles feat(migrations): scaffold compass migrations

packages/web/src/__tests__/__mocks__/mock.render.tsx, packages/web/src/routers/index.tsx
This pull request updates the React Router configuration to enable new v7 features and future-proof routing behavior. The main changes are the addition of the `future` prop with specific flags in both the test mock provider and the main router setup.
Closes #1049 
Routing configuration updates:
* Added the `future` prop to the `BrowserRouter` in `mock.render.tsx` to enable `v7_startTransition` and `v7_relativeSplatPath` features, which prepare the codebase for React Router v7 improvements.
* Updated the `createBrowserRouter` call in `routers/index.tsx` to include the `future` option with `v7_relativeSplatPath`, ensuring consistent route matching and compatibility with upcoming router changes.
General code organization:
* Refactored the router array argument in `routers/index.tsx` for …
=> feat(web): opt-in to react-router v7 features
